### ISSUE TITLE
This repository is in violation of Unity Asset Store's terms.

### ISSUE THREAD

**Issue by EnoxSoftware** [A7ocin/PPOL#1]
Hi.
I am a developer of "OpenCVForUnity".
Your public repository contains the files of the paid Unity asset that I am selling in the asset store.
Could you add the "OpenCVForUnity" folder to the .ignore file or change the attribute of the repository to private?
I hope that you will understand.
Thank you in advance.

Enox Software

**Comment by A7ocin** [comment]
Hi, I'm sorry, I completely forgot to do it.
Of course I can fix it, I'll do it now.

Thank you for the advice and for the great asset you are providing.

Nicola

**Comment by EnoxSoftware** [comment]
Hi Nicola.

Thank you for your quick response the other day.
I noticed that the asset files remained included in past commits in your repository.
Could you delete the files completely using the "git filter - branch" command, etc?

Thank you in advance.

Enox Software
